### ISSUE TITLE
Setting Hidden Fields' Inputs

### ISSUE THREAD

**Issue by francesharlow** [persephone-admissions/admissions_app#35]
Hi, 

Here's a different issue that arose while trying to figure out Paperclip...

I'm trying to establish my variables so that, when someone is logged in as a student, they can apply for a course and the application form will automatically attach their user id and the course's id to the newly instantiated application.

Here's the url: http://127.0.0.1:3000/courses/1/applications/new

As such, I've defined them in the applications_controller:

```
    @student_id = session[:user_id]
    @course_id = params[:id]
```

to be used in the _form 

```
<div class="field">
    <%= hidden_field_tag(:student_id, @student_id) %>
  </div>
  <br>
  <div class="field">
  <%= hidden_field_tag(:course_id, @course_id) %>
  </div>
```

I thought for sure I had this working last night, but it appears to be broken now. I can create new users but they lack both student and course ids. Do you have any suggestions?

Thanks!

**Comment by phlco** [comment]
My suggestion is to just do it in the controller. If you get all the information back.

Put a binding.pry inside the controller action that you want to investigate.

**Comment by phlco** [comment]
Remember! You're just trying to render HTML in the end so if you can't get it to work, just start with the hard coded HTML

```
<input type="hidden" name="student_id" value="<%= student.id %>">
```

if you see a form helper method with "_tag", it usually has a corresponding one that you can call on the form builder object.

```
<%= hidden_field_tag %> 
# vs
<%= f.hidden_field %>
```
