### ISSUE TITLE
git 

### ISSUE THREAD

**Issue by icusick** [persephone-admissions/admissions_app#51]
i want to pull from master so i can undo all the changes i've made on the branch but it won't let me because it wants me to commit those changes. the point is that i want to get rid of those changes. i've tried switching to a new branch but the changes are following me around. how do i deal with this?

**Comment by icusick** [comment]
by the way, this is why i deleted my local repo and recloned a bunch of times yesterday.

**Comment by phlco** [comment]
You need to run `git status` and read the output. It will tell you the state of your repository and branch.

If you want to get rid of changes that haven't been committed yet run `git checkout -- <filename>` where "<filename>" is whatever you want to get rid of.  So to undo changes to a file called index.html you'd write 

```
git checkout -- index.html
```

To remove files from staging try `git reset HEAD <file>` following the same pattern. 

If you have files that have never been added to git they're "untracked" if you don't want those either you can just delete them.
